name: Enforce Semi-Linear History

on:
  pull_request:
    types:
      - synchronize
      - opened

jobs:
  check-history:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0 # Fetch all history so we can check the entire branch

    - name: Install GitHub CLI
      run: |
        sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-key C99B11DEB97541F0
        sudo apt-add-repository https://cli.github.com/packages
        sudo apt update
        sudo apt install gh

    - name: Authenticate with GitHub CLI
      run: gh auth login --with-token <<< "${{ secrets.GITHUB_TOKEN }}"

    - name: Enforce semi-linear history
      run: |
        # Get the target branch name
        TARGET_BRANCH=$(gh pr view ${GITHUB_REF} --json baseRefName -q '$.baseRefName')

        # Get the SHA of the latest commit on the target branch
        LATEST_TARGET_COMMIT=$(git rev-parse origin/${TARGET_BRANCH})

        # Get the SHA of the commit where the PR branch diverged
        MERGE_BASE_COMMIT=$(git merge-base origin/${TARGET_BRANCH} HEAD)

        # Check if the divergent commit is the latest commit on the target branch
        if [ "${MERGE_BASE_COMMIT}" != "${LATEST_TARGET_COMMIT}" ]; then
          echo "Error: Your branch must be created from the latest commit on ${TARGET_BRANCH}."
          exit 1
        fi
