name: Check if .py imports have been sorted by isort

on:
  - push

jobs:
  check-format-isort:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - uses: isort/isort-action@master
        with:
          configuration: "--check-only --diff --profile black"
          requirementsFiles: "requirements.txt"
